### ISSUE TITLE
Failed to resolve: com.github.tangem.tangem-sdk-android:tangem-core:3.6.2

### ISSUE THREAD

**Issue by bh1r123** [tangem/tangem-sdk-android-old#180]
Hi There,

I am unable to download the lib from android studio always getting the above error. added all the steps specified in the below document still facing the issue. Can you please help me to fix this asap

Document Link : https://developers.tangem.com/getting-started/android

**Comment by gbixahue** [comment]
try replacing by this
```
implementation "com.github.tangem.tangem-sdk-android:android:$latestVersion"
implementation "com.github.tangem.tangem-sdk-android:core:$latestVersion"
```

We will fix it in the documentation soon

**Comment by bh1r123** [comment]
Getting the below error 

Could not get unknown property 'latestVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by gbixahue** [comment]
latestVersion - it's a string variable which contains "3.6.2"
```
implementation "com.github.tangem.tangem-sdk-android:android:3.6.2"
implementation "com.github.tangem.tangem-sdk-android:core:3.6.2"
```

**Comment by FogelAO** [comment]
Documentation is still not up to date, getting same error...
