### ISSUE TITLE
Duplicate values in `TlvTag`

### ISSUE THREAD

**Issue by LimpidCrypto** [tangem/tangem-sdk-android-old#190]
## Description
For the [`TlvTag`](https://github.com/tangem/tangem-sdk-android/blob/master/tangem-sdk-core/src/main/java/com/tangem/common/tlv/TlvTag.kt#L30) enum there are [`InteractionMode`](https://github.com/tangem/tangem-sdk-android/blob/master/tangem-sdk-core/src/main/java/com/tangem/common/tlv/TlvTag.kt#L78) and [`WriteFileMode`](https://github.com/tangem/tangem-sdk-android/blob/master/tangem-sdk-core/src/main/java/com/tangem/common/tlv/TlvTag.kt#L138) which both have a value of `0x23`. I just want to reassure if that's correct.
There is also a duplicate [`CardIdManufacturerSignature`](https://github.com/tangem/tangem-sdk-android/blob/master/tangem-sdk-core/src/main/java/com/tangem/common/tlv/TlvTag.kt#L67) which is not really an urgent issue but may be a nit to fix with next push.

**Comment by gbixahue** [comment]
Thanks for your carelessness. Technically, they are not errors. These are duplicates that need to be removed.

**Comment by LimpidCrypto** [comment]
> Thanks for your carelessness. Technically, they are not errors. These are duplicates that need to be removed.

Thanks for your quick answer :)
So it is correct, that `InteractionMode` and `WriteFileMode` both have the same value or should one have another, or should one be omitted?

**Comment by gbixahue** [comment]
Technically, they are not errors - both have the same value.
This will be fixed in the next release.

**Comment by gbixahue** [comment]
Fixed in https://github.com/tangem/tangem-sdk-android/pull/192
