### ISSUE TITLE
Legacy support libraries are detected (AndroidX support).

### ISSUE THREAD

**Issue by ghost** [tangem/tangem-sdk-android-old#191]
### Version
3.6.2

### Issue:
Attempt to remove support for legacy `support libraries` causes a warning and performance issue:

```
The following legacy support libraries are detected:
app -> com.github.tangem.tangem-sdk-android:android:3.6.2 -> at.favre.lib:armadillo:0.9.0 -> com.android.support:support-annotations:28.0.0
```
### Steps to reproduce:
 - Apply the latest dependency `com.github.tangem.tangem-sdk-android:android:3.6.2`
 - In the gradle.properties file apply `android.enableJetifier=false`
 
 ### Suggestions:
 Update the legacy dependency `at.favre.lib:armadillo:0.9.0` to `at.favre.lib:armadillo:1.0.0+`
 
 Thanks.

**Comment by gbixahue** [comment]
Thank you. This will be fixed in the next release.

**Comment by gbixahue** [comment]
Fixed in https://github.com/tangem/tangem-sdk-android/pull/193

**Comment by FogelAO** [comment]
This one is still actual since 3.6.2 is still latest version
