### ISSUE TITLE
Try Again. Failed to send a transaction (400)

### ISSUE THREAD

**Issue by thiago-tsnnst** [tangem/tangem-sdk-android-old#2]
Hi guys, im getting this error in the app, and i cant understand what is happening. Tangem is offline? Its something in my app or device? The message is too generic.

**Comment by lazutkin-andrey** [comment]
Hi! 
Sorry for the late reply. This repository is about Tangem Cards SDK. 
If you're experiencing any issues with Tangem App, please try to update your app to the latest or request support from info@tangem.com
