### ISSUE TITLE
tangem-sdk-android/android sources are not included in v3.7.1

### ISSUE THREAD

**Issue by N3TC4T** [tangem/tangem-sdk-android-old#236]
Thanks for fixing https://github.com/tangem/tangem-sdk-android/issues/225 but now it seems sources for `tangem-sdk-android/android` is not included in version `3.7.1`. this is necessary for other platforms SDK's like `react-native` 

<img width="500"  src="https://user-images.githubusercontent.com/6250203/227910497-c5f55652-11f0-4302-8dee-7cadc802375d.png">

@kozarezvlad

**Comment by WietseWind** [comment]
@kozarezvlad @lazutkin-andrey

# Can you please give this **HIGH** priority? This is a showstopper for us and we've been waiting for quite some time.

**Comment by kozarezvlad** [comment]
Sorry for delay, we have an issue in build scripts.
Looking for solution asap

**Comment by kozarezvlad** [comment]
@N3TC4T @WietseWind fixed for 3.7.2

**Comment by N3TC4T** [comment]
Thanks @kozarezvlad, appreciate it.
