### ISSUE TITLE
Document Ethereum signMessage part

### ISSUE THREAD

**Issue by fulldecent** [tangem/tangem-sdk-android-old#3]
Please add documentation of how to achieve equivalent of https://docs.ethers.io/v5/api/signer/#Signer-signMessage

**Comment by lazutkin-andrey** [comment]
Hi, thanks for the question!
Take a look at signing section here https://github.com/Tangem/tangem-sdk-android#sign

Also, we have a demo project https://github.com/Tangem/tangem-sdk-android/tree/master/tangem-demo

Let me know if you have other questions.

**Comment by dbaturin** [comment]
I'd like to add that you should provide 256 bit hash to sign with secp256k1 curve. For Ethereum you should hash your message with Keccak256.

Signature from card might not be canonical (have "high S" value) so you should also canonicalize it first, most crypto libraries can do that.
